myName = input("What's you name?:")
myFood = input("What's your favorite food?:")
myMusic = input("What's your favorite music?:")
doLive = input("Where do you live?:")
print("Great, lest go!")
print()
print("You are")
print(myName)
print("You're probably hungry for")
print(myFood)
print("and you're definitely getting your groove on to")
print(myMusic)
print("living in the amazing")
print(doLive)
